---
name: "Molecule"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch: null

defaults:
  run:
    working-directory: "organicveggie.vagrant"

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out the codebase."
        uses: "actions/checkout@v2"
        with:
          path: "organicveggie.vagrant"

      - name: "Set up Python 3."
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.x"

      - name: "Install lint dependencies."
        run: "pip3 install yamllint ansible ansible-lint"

      - name: "Run linters"
        run: |
          yamllint -c .yamllint -f github -s .
          ansible-lint
        working-directory: "organicveggie.vagrant"

  molecule:
    name: "Molecule"
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        distro:
          - "centos8"
          - "ubuntu2204"
          - "ubuntu2004"
          - "ubuntu1804"
          - "debian11"
          - "debian10"
          - "fedora34"
          - "fedora33"

    steps:
      - name: "Check out the codebase."
        uses: "actions/checkout@v2"
        with:
          path: "organicveggie.vagrant"

      - name: "Set up Python 3."
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.x"
      
      - name: "Install python dependencies"
        run: "pip install ansible docker molecule molecule-docker"
      
      - name: "Run Molecule tests"
        run: "molecule test"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: "${{ matrix.distro }}"

      # - name: "Install tox"
      #   run: >
      #     python -m pip install tox

      # - name: "Run Molecule tests."
      #   run: "tox -- --debug test"
      #   env:
      #     PY_COLORS: '1'
      #     ANSIBLE_FORCE_COLOR: '1'
      #     MOLECULE_DISTRO: "${{ matrix.distro }}"
